#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

timezone: "Asia/Shanghai"

images:
  agent:
    repository: inlong/agent
    tag: latest
  dashboard:
    repository: inlong/dashboard
    tag: latest
  dataproxy:
    repository: inlong/dataproxy
    tag: latest
  tubemqManager:
    repository: inlong/tubemq-manager
    tag: latest
  tubemqServer:
    repository: inlong/tubemq-all
    tag: latest
  manager:
    repository: inlong/manager
    tag: latest
  audit:
    repository: inlong/audit
    tag: latest
  mysql:
    repository: mysql
    tag: 5.7
  zookeeper:
    repository: zookeeper
    tag: latest
  initContainer:
    repository: busybox
    tag: latest
  pullPolicy: "IfNotPresent"

volumes:
  persistence: false
  storageClassName: "local-storage"

affinity:
  anti_affinity: false

ingress:
  enabled: false
  hosts:

agent:
  component: "agent"
  replicaCount: 1
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  ports:
    agent: 8008
    managerOpenApi: ${manager.containerPort}
    dataProxy: ${dataproxy.containerPort}

dashboard:
  component: "dashboard"
  replicaCount: 1
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  ports:
    webPort: 80
    webNodePort: 30080
  service:
    type: LoadBalancer

dataproxy:
  component: "dataproxy"
  replicaCount: 1
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  containerPort: 46801
  managerOpenApiPort: ${manager.containerPort}

tubemqManager:
  component: "tubemq-manager"
  replicaCount: 1
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  containerPort: 8089

manager:
  component: "manager"
  replicaCount: 1
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  ports:
    webPort: 8083
  username: "root"
  password: "inlong"

audit:
  component: "audit"
  replicaCount: 1
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  ports:
    webPort: 10081

# If not exists external MySQL, InLong will use it.
mysql:
  component: "mysql"
  replicaCount: 1
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  username: "root"
  password: "inlong"
  ports:
    server: 3306
  volumes:
    name: data
    size: "10Gi"

zookeeper:
  component: "zookeeper"
  replicaCount: 3
  updateStrategy:
    type: "RollingUpdate"
  podManagementPolicy: "OrderedReady"
  ports:
    client: 2181
    follower: 2888
    leaderElection: 3888
  probe:
    liveness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 10
      periodSeconds: 30
    readiness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 10
      periodSeconds: 30
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
  tolerations: []
  gracePeriod: 30
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  volumes:
    name: data
    size: "10Gi"
  service:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  pdb:
    usePolicy: true
    maxUnavailable: 1

tubemqMaster:
  component: "tubemq-master"
  replicaCount: 1
  updateStrategy:
    type: "RollingUpdate"
  podManagementPolicy: "OrderedReady"
  ports:
    rpcPort: 8715
    webPort: 8080
    helpPort: 9001
  probe:
    liveness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 10
      periodSeconds: 30
    readiness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 10
      periodSeconds: 30
  tolerations: []
  gracePeriod: 30
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  volumes:
    name: data
    size: "10Gi"
  service:
    type: LoadBalancer
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  pdb:
    usePolicy: true
    maxUnavailable: 1

tubemqBroker:
  component: "tubemq-broker"
  replicaCount: 1
  updateStrategy:
    type: "RollingUpdate"
  podManagementPolicy: "OrderedReady"
  ports:
    rpcPort: 8123
    webPort: 8081
  probe:
    liveness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 10
      periodSeconds: 30
    readiness:
      enabled: true
      failureThreshold: 10
      initialDelaySeconds: 10
      periodSeconds: 30
  tolerations: []
  gracePeriod: 30
  resources:
    requests:
      cpu: 0.5
      memory: "512Mi"
  volumes:
    name: data
    size: "10Gi"
  service:
    type: LoadBalancer
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  pdb:
    usePolicy: true
    maxUnavailable: 1

# InLong will use the external Services.
external:
  mysql:
    enabled: false
    hostname: "localhost"
    port: 3306
    username: "root"
    password: "password"
  pulsar:
    enabled: false
    serviceUrl: "pulsar://localhost:6650"
    adminUrl: "http://localhost:8080"